### ISSUE TITLE
[Bug]: Some inconsistencies in x and y axis labels displayed (AreaChart)

### ISSUE THREAD

**Issue by Ignotos** [gsoft-inc/ov-igloo-ui#304]
### Contact Details

michael.ignoto@gsoft.com

### What happened?

example screenshot for reference: 
![image](https://user-images.githubusercontent.com/15761411/211091683-0e67712c-f551-4c2a-9e95-2c1024c3441e.png)

1. For x-axis labels, it would be preferable to show as many dates as we can allow. In the example, we have the last 7 days + the current day (8 days total), there is room to show all days but some are skipped (Jan 1, Jan 3, Jan 5). 

2. For the y-axis labels, in some instances not all numbers in the range are included, in the example I would expect all numbers 0 - 5 to be shown but only 0, 2, and 5 are shown. the range provided is min: 0 max: 5. Most of the time the y-axis labels are fine, but in this case with little data and a small range it doesn't behave like I would expect. 

### Component

AreaChart

### Component Version

2.0.0

### Which browsers are you seeing the problem on?

Firefox, Chrome, Microsoft Edge

**Comment by vicky-comeau** [comment]
Hi, can you provide what you put for the dataSet and dateRange please, thanks.

**Comment by franckgaudin** [comment]
> For x-axis labels, it would be preferable to show as many dates as we can allow. In the example, we have the last 7 days + the current day (8 days total), there is room to show all days but some are skipped (Jan 1, Jan 3, Jan 5).

The component is configured to divide the number of elements by 7 and it automatically calculates which element to display. To fix the rendering we can add a property that allows to change this value for example in our case 8 which corresponds to the desired display. 

<img width="662" alt="Capture d’écran, le 2023-01-16 à 14 14 05" src="https://user-images.githubusercontent.com/2379339/212751429-0b65c094-0459-4b6b-907e-ced800d42fe7.png">

> For the y-axis labels, in some instances not all numbers in the range are included, in the example I would expect all numbers 0 - 5 to be shown but only 0, 2, and 5 are shown. the range provided is min: 0 max: 5. Most of the time the y-axis labels are fine, but in this case with little data and a small range it doesn't behave like I would expect.

The calculation of the Y axis is similar to the X axis for a better result we can choose a range of 0-6 ou 0-4 to divide the elements by 2.

<img width="656" alt="Capture d’écran, le 2023-01-16 à 14 17 43" src="https://user-images.githubusercontent.com/2379339/212751883-d3a3bcbf-5c12-497f-96a1-e9e48cdf7b6a.png">

Another option is to leave the props range empty so that the component calculates the spacing itself. It all depends on the desired result.

<img width="661" alt="Capture d’écran, le 2023-01-16 à 14 19 18" src="https://user-images.githubusercontent.com/2379339/212752089-70675f8f-c47e-4315-967f-2b1ac74cc51b.png">

**Comment by Ignotos** [comment]
I think allowing us specify the number of elements on the x-axis could be a good solution to this. As long as the chart remains responsive, so if the labels don't all fit on a mobile screen only a subset are shown so that there is no overlap between labels.

Another option would be to make the default 8 ticks, since this seems to have been the default in the reports up until now across OV (the chart always shows 7 previous days + current date for 8 total days). Either option is OK for me. 

Also one more small thing related to this that I forgot to mention, seems the design team would like to have a specific date standard across all of OV, they seem correct for the French labels but for the English labels they are missing a period when the name is abbreviated, here is what the standard is: 

english (example "Jan. 1" instead of "Jan 1"):
![image](https://user-images.githubusercontent.com/15761411/212945576-5f84d605-7b29-49b8-bf4d-84d42c0cca38.png)

french (seems correct already): 
![image](https://user-images.githubusercontent.com/15761411/212945673-99ce37a3-0f90-4743-af6b-8876625d0e15.png)
