### ISSUE TITLE
[Bug]: The modal with isClosable=false displays the x button in desktop

### ISSUE THREAD

**Issue by CarolineSabourin-Jean** [gsoft-inc/ov-igloo-ui#327]
### What happened?

The modal with isClosable=false displays the x button in desktop.

![image](https://user-images.githubusercontent.com/25105785/216190240-b79146af-5b0b-4e73-a5dc-d3c2864835c0.png)

### Component

Modal

### Component Version

1.1.0

**Comment by vicky-comeau** [comment]
This bug has been fixed. The close button does not show on desktop if isClosable is set to false. It will show on mobile if isDismissable is set to true since the overlay no longer shows on mobile.
If isClosable and isDismissable are both set to false, a custom button must be added to be able to close the dialog.
