### ISSUE TITLE
[Bug]: TagPicker text color on hasError

### ISSUE THREAD

**Issue by JeffreyLYT** [gsoft-inc/ov-igloo-ui#462]
### Contact Details

jeffrey.lam@gsoft.com

### What happened?

When the _hasError_ property for the TagPicker component is set to true, the border becomes red but the text remains the same default color.

![image](https://github.com/gsoft-inc/ov-igloo-ui/assets/43586477/852c9e45-79f9-462c-9991-d46da374c358)

### Component

TagPicker

### Component Version

0.3.1

**Comment by vicky-comeau** [comment]
This is as expected. I had a talk with Design and because we can set hasError to any of the appearances, it wouldn't make sense to change the font color if we had a green background for example.
In the future, this will be revised. We have a JIRA open to turn the hasError prop into an appearance instead: https://gsoftdev.atlassian.net/browse/OV-45087
